### PR TITLE
use python3 instead to fix awscli breaking 

### PR DESCRIPTION
**Pull request by jcputter**
```
== START LOGIN
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python2.7/site-packages/awscli/clidriver.py", line ***, in <module>
    import botocore.session
  File "/usr/lib/python2.7/site-packages/botocore/session.py", line 29, in <module>
    import botocore.configloader
  File "/usr/lib/python2.7/site-packages/botocore/configloader.py", line 19, in <module>
    from botocore.compat import six
  File "/usr/lib/python2.7/site-packages/botocore/compat.py", line [27], in <module>
    from dateutil.tz import tzlocal
  File "/usr/lib/python2.7/site-packages/dateutil/__init__.py", line 5, in <module>
    from ._version import version as __version__
  File "/usr/lib/python2.7/site-packages/dateutil/_version.py", line 10
    version: str
           ^
SyntaxError: invalid syntax

### CODE REVIEW

**Comment by brunopadz** [comment]
Installing `python-dateutil-2.8.2` also solves the issue. But yeah +1 to merge it ASAP. :)

**Comment by rkorebrits-paystack** [comment]
@jcputter @kciter Thanks! Works again - can we expect a new release soon?

**Comment by giopunt** [comment]
> @jcputter @kciter Thanks! Works again - can we expect a new release soon?

you can already target tag v5, `kciter/aws-ecr-action@v5`

**Comment by kciter** [comment]
@brunopadz @rkorebrits-paystack @giopunt 
I've just released v5.

**Pull request merged**
